### ISSUE TITLE
why my bundle.css is this?

### ISSUE THREAD

**Issue by samchanye** [thgh/rollup-plugin-css-only#2]
``` css
export default __$styleInject(".book{color:blue;-webkit-transform:translateX(30px);transform:translateX(30px)}",undefined);
```
hello, Why my bundle is this content? i can't use it by my .html file by link; because it is the function call in the .js file 

``` javascript
function __$styleInject(css, returnValue) {
  if (typeof document === 'undefined') {
    return returnValue;
  }
  css = css || '';
  var head = document.head || document.getElementsByTagName('head')[0];
  var style = document.createElement('style');
  style.type = 'text/css';
  if (style.styleSheet){
    style.styleSheet.cssText = css;
  } else {
    style.appendChild(document.createTextNode(css));
  }
  head.appendChild(style);
  return returnValue;
}
```
