### ISSUE TITLE
Nested import handling

### ISSUE THREAD

**Issue by jerekshoe** [thgh/rollup-plugin-css-only#28]
When css is imported from modules that are being imported themselves, I'm uncertain if the order is as it should be. I'm coming from using `css-loader` with webpack, which from what I have seen handles css imports the same way that javascript imports are handled (i.e. each imported modules code/imports are executed recursively before the next import statement is handled). This seems to contradict #16, however, so I'm curious what the intended functionality is for this plugin.

#### main.js
```javascript
import './a.js';
import './a.css';
```

#### a.js
```javascript
import './b.css';
```

#### a.css
```css
body {
    background-color: red;
}
```

#### b.css
```css
body {
    background-color: blue;
}
```

#### bundle.css
```css
body {
    background-color: blue;
}body {
    background-color: red;
}
```
#### bundle.css
```css
body {
    background-color: red;
}body {
    background-color: blue;
}
```
